In [1]:
import numpy as np
import tensorflow as tf
from layers import Readout
from utils import seed_everything
import config as C
seed_everything(C.SEED)

# Define Data

In [2]:
x1 = np.array([[1, 1, 1, 1], [0, 0, 0, 0], [0, 0, 0, 0]], dtype=np.float32)
x1

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [3]:
x2 = np.array([[0, 0, 0, 0], [1, 1, 1, 1], [0, 0, 0, 0]], dtype=np.float32)
x2

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.]], dtype=float32)

In [4]:
x3 = np.array([[0, 0, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1]], dtype=np.float32)
x3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.]], dtype=float32)

# Node Wise MLP Readout

In [5]:
readout = Readout(2, mode='mlp')

In [6]:
readout(x1)

LOG >>> x
[[1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
LOG >>> weight
[<tf.Variable 'readout/dense/kernel:0' shape=(4, 2) dtype=float32, numpy=
array([[ 0.3291242 , -0.11798644],
       [-0.294235  , -0.07103491],
       [-0.9326792 ,  0.3693447 ],
       [ 0.48023486,  0.744889  ]], dtype=float32)>]
LOG >>> output
[[-0.4175551  0.9252124]
 [ 0.         0.       ]
 [ 0.         0.       ]]


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.5076573, 0.       , 0.       ], dtype=float32)>

In [7]:
readout(x2)

LOG >>> x
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]]
LOG >>> weight
[<tf.Variable 'readout/dense/kernel:0' shape=(4, 2) dtype=float32, numpy=
array([[ 0.3291242 , -0.11798644],
       [-0.294235  , -0.07103491],
       [-0.9326792 ,  0.3693447 ],
       [ 0.48023486,  0.744889  ]], dtype=float32)>]
LOG >>> output
[[ 0.         0.       ]
 [-0.4175551  0.9252124]
 [ 0.         0.       ]]


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.       , 0.5076573, 0.       ], dtype=float32)>

In [8]:
readout(x3)

LOG >>> x
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]
LOG >>> weight
[<tf.Variable 'readout/dense/kernel:0' shape=(4, 2) dtype=float32, numpy=
array([[ 0.3291242 , -0.11798644],
       [-0.294235  , -0.07103491],
       [-0.9326792 ,  0.3693447 ],
       [ 0.48023486,  0.744889  ]], dtype=float32)>]
LOG >>> output
[[ 0.         0.       ]
 [ 0.         0.       ]
 [-0.4175551  0.9252124]]


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.       , 0.       , 0.5076573], dtype=float32)>

# Node Wise Mean Readout 

In [9]:
readout = Readout(2, mode='mean')

In [10]:
readout(x1)

LOG >>> x
[[1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
LOG >>> output
[1. 0. 0.]


<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [11]:
readout(x2)

LOG >>> x
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]]
LOG >>> output
[0. 1. 0.]


<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [12]:
readout(x3)

LOG >>> x
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]
LOG >>> output
[0. 0. 1.]


<tf.Tensor: shape=(), dtype=float32, numpy=1.0>